server.port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:6541/devskills
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  data:
    redis:
      host: localhost
      port: 6544
      password: pass
