server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:6542/devskills-questions
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
